layout_spectrum: 0.4441461
color:
  saturation: 1
  lightness: 0.9274973
  brandStrength: 0.7513427
  brandColors:
    - '#161516'
    - '#27ACE1'
    - '#FAD042'
    - '#E02F31'
    - '#998A77'
  rhythmicContrast: 0.9081632
typography_spectrum: 0.09505906
name: Camp Straight Street
